export const DEPARTMENTS = [
  'Medicine',
  'Surgery',
  'Pediatrics',
  'Cardiology',
  'Neurology',
  'Oncology',
  'Psychiatry',
  'Radiology',
  'Pathology',
  'Anesthesiology',
  'Emergency Medicine',
  'Family Medicine',
  'Internal Medicine',
  'Obstetrics and Gynecology',
  'Orthopedics',
  'Ophthalmology',
  'Otolaryngology',
  'Dermatology',
  'Urology',
  'Public Health',
  'Nursing',
  'Pharmacy',
  'Dentistry',
  'Physical Therapy',
  'Occupational Therapy',
  'Medical Technology',
  'Health Administration',
  'Biomedical Engineering',
  'Clinical Research',
  'Health Informatics',
  'Rural Health',
  'Artificial Intelligence',
  'Diagnostic Imaging',
  'Other',
];
